### ISSUE TITLE
Suggestion - Toggling it's functionality off when generating the world for the first time

### ISSUE THREAD

**Issue by OlaPessoa** [VidTu/Ksyxis#27]
This mod when mixed together with Seamless Loading Screen, HAS A HUGE PERFORMANCE INCREASE WHEN JOINING THE WORLD, therefore i had this idea, that whenever you're creating a new world, Ksyxis way of working can be toggled off (like a option in a config file) so that at first it generates the world normally, then after leaving the world and joining again, ksyxis works like normal, skips the loading of the chunks while seamless loading screen would work as a charm as well, making these 2 the best combination there is (i'll sugest this on seamless loading screen's github as well)

**Comment by VidTu** [comment]
the problem with all of that is, **ksyxis has no direct access to the game and doesn't know which version or mappings it runs on**. due to how i decided to implement everything (for multi-version, multi-loader support for different mappings, all in one jar), it is really impossible to know anything about the game (including whether this is the first load) at the moment of loading. while config options and even UI can be made, it'll require some real hacky ways to do it and probably break a lot of things. if you really want some sort of customizability, i'd suggest using the "fast load" mod.

**Comment by OlaPessoa** [comment]
> the problem with all of that is, **ksyxis has no direct access to the game and doesn't know which version or mappings it runs on**. due to how i decided to implement everything (for multi-version, multi-loader support for different mappings, all in one jar), it is really impossible to know anything about the game (including whether this is the first load) at the moment of loading. while config options and even UI can be made, it'll require some real hacky ways to do it and probably break a lot of things. if you really want some sort of customizability, i'd suggest using the "fast load" mod.

thank you for the response man, but... i've tried fast load already and there's no config file for it ; - ; at least not on 1.20.1, + Ksyxis is better, as far as i'm concerned, specially since fast load doesn't seem to even work on 1.20.1 (forge)

**Comment by VidTu** [comment]
then i don't understand why you need a toggle for "first-time" world generation. if you need first-time generation, use fast load (and ask authors to fix it), if you don't want first-time world generation, use ksyxis. if you also want to eliminate any "fall-through-world-while-spawn-chunks-are-still-generating" scenarios that might occur with ksyxis, you can use some general-purpose server (including integrated server for singleplayer) optimization mods like lithium, c2me, noisium, modernfix, vmp, etc.
