### ISSUE TITLE
1.21 "INVALID MESSAGE WITH QUOTES: use the GRAVE ACCENT /x60 instead."

### ISSUE THREAD

**Issue by NotNovaCraft** [VidTu/Ksyxis#35]
I dont know why this comes up. Help.

**Comment by VidTu** [comment]
check the logs

**Comment by VidTu** [comment]
while the underlying issue can't be fixed without you providing the logs, the mod works fine for me with all 1.21(.1) loaders, the "grave accent" error message has been fixed in https://github.com/VidTu/Ksyxis/commit/32dce3c57d721ecaffa333a8d5514b8a240977cc.
updated mod version will be released in a while.
